language: node_js
node_js:
- '4.3'
sudo: false
env:
- L10N_LOCALE_SRC="locales" L10N_LOCALE_DEST="dist/locales"
cache:
  directories:
  - node_modules
  - locale
deploy:
  provider: heroku
  api_key:
    secure: C/eOW0vXt30EUSbxlqQawBX1i28PX8dBuFgmfOAbYEY+xYOOcJ7oDWbgXXhrD1q/mc4cfgWHHmC0cgAQ8rqcpLyDscgqsoEQp+qt/IUA9tiSx95PVjkn4z+UtLrcd8HoyMdLbBmsbhriZys5Kzwl9Weqvi3at33pmUhFs+Mb2aM=
  app: bramble-staging
  on:
    repo: mozilla/thimble.mozilla.org
    branch: bramble
