language: node_js
node_js:
- '4.3'
sudo: false
env:
  global:
  - L10N_LOCALE_SRC: locales
  - L10N_LOCALE_DEST: dist/locales
  - secure: EAbCzlvar10vLD/tkch8k7aeJj55AG5puDLIdj8CcqE9oBIplhZMMkEfLYCFYkubm0eIKMKnbSRqs/pddjebiQwGmjzWBN5Lhf6U3k7df36UB4WQwbisl88jxTKWmve4vLtYeJBuVQrr4eFxeB0OY0davbrmGItETG0ZaQYrJjY=
cache:
  directories:
  - node_modules
after_script:
- bash ./scripts/localize-brackets.sh
deploy:
  provider: heroku
  api_key:
    secure: E2houbiE3BVUltZqlMlaCIUOoAjecJTFVi/J5+TPGV04ZPitOXNs5NXsZ21nSBYRapTdUwDI3ulD54fgR50vlOnW/FWnC3NdSjqWrCJDpGzXnSYRzPFeAejs8DtNvIsBvjLoLDS8eK5L4tlW7swyiFV2huAXloqKNR6LnvEFzVQ=
  app: bramble-staging
  on:
    repo: mozilla/thimble.mozilla.org
    branch: master
